// ghrd_10as066n2_alt_serdes_10_vaq6iza.v

// This file was auto-generated from alt_serdes_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 16.1 203

`timescale 1 ps / 1 ps
module ghrd_10as066n2_alt_serdes_10_vaq6iza (
		input  wire [0:0] data_in_export,      //      data_in.export
		input  wire       clk_export,          //          clk.export
		input  wire       loaden_export,       //       loaden.export
		input  wire       div_clk_export,      //      div_clk.export
		input  wire [7:0] hs_phase_export,     //     hs_phase.export
		input  wire       locked_export,       //       locked.export
		output wire [3:0] data_s_export,       //       data_s.export
		output wire [0:0] delay_locked_export  // delay_locked.export
	);

	ghrd_10as066n2_altera_lvds_161_l5lsykq alt_serdes_in (
		.rx_in          (data_in_export),      //          rx_in.export
		.rx_out         (data_s_export),       //         rx_out.export
		.ext_fclk       (clk_export),          //       ext_fclk.export
		.ext_loaden     (loaden_export),       //     ext_loaden.export
		.ext_coreclock  (div_clk_export),      //  ext_coreclock.export
		.ext_vcoph      (hs_phase_export),     //      ext_vcoph.export
		.ext_pll_locked (locked_export),       // ext_pll_locked.export
		.rx_dpa_locked  (delay_locked_export)  //  rx_dpa_locked.export
	);

endmodule
