// ghrd_10as066n2_alt_serdes_10_jgwqmpq.v

// This file was auto-generated from alt_serdes_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 16.1 203

`timescale 1 ps / 1 ps
module ghrd_10as066n2_alt_serdes_10_jgwqmpq (
		output wire [0:0] data_out_export, // data_out.export
		input  wire       clk_export,      //      clk.export
		input  wire       loaden_export,   //   loaden.export
		input  wire       div_clk_export,  //  div_clk.export
		input  wire [3:0] data_s_export    //   data_s.export
	);

	ghrd_10as066n2_altera_lvds_161_weuvy6y alt_serdes_out (
		.tx_in         (data_s_export),   //         tx_in.export
		.tx_out        (data_out_export), //        tx_out.export
		.ext_fclk      (clk_export),      //      ext_fclk.export
		.ext_loaden    (loaden_export),   //    ext_loaden.export
		.ext_coreclock (div_clk_export)   // ext_coreclock.export
	);

endmodule
