// ghrd_10as066n2_alt_serdes_10_ruc4yeq.v

// This file was auto-generated from alt_serdes_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 16.1 203

`timescale 1 ps / 1 ps
module ghrd_10as066n2_alt_serdes_10_ruc4yeq (
		input  wire       rst_reset,       //      rst.reset
		input  wire       ref_clk_clk,     //  ref_clk.clk
		output wire       locked_export,   //   locked.export
		output wire [7:0] hs_phase_phout,  // hs_phase.phout
		output wire [1:0] hs_clk_lvds_clk, //   hs_clk.lvds_clk
		output wire [1:0] loaden_loaden,   //   loaden.loaden
		output wire       ls_clk_clk       //   ls_clk.clk
	);

	ghrd_10as066n2_altera_iopll_161_sacslaa alt_serdes_pll (
		.rst      (rst_reset),       //    reset.reset
		.refclk   (ref_clk_clk),     //   refclk.clk
		.locked   (locked_export),   //   locked.export
		.phout    (hs_phase_phout),  //    phout.phout
		.lvds_clk (hs_clk_lvds_clk), // lvds_clk.lvds_clk
		.loaden   (loaden_loaden),   //   loaden.loaden
		.outclk_2 (ls_clk_clk)       //  outclk2.clk
	);

endmodule
