// ghrd_10as066n2_alt_serdes_10_v6injpq.v

// This file was auto-generated from alt_serdes_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 16.1 203

`timescale 1 ps / 1 ps
module ghrd_10as066n2_alt_serdes_10_v6injpq (
		input  wire       clk_export,     //     clk.export
		input  wire [1:0] din_export,     //     din.export
		output wire [0:0] pad_out_export  // pad_out.export
	);

	ghrd_10as066n2_altera_gpio_161_ojngebi alt_serdes_out (
		.ck      (clk_export),     //      ck.export
		.din     (din_export),     //     din.export
		.pad_out (pad_out_export)  // pad_out.export
	);

endmodule
