// ghrd_10as066n2_altera_mm_interconnect_161_5qx5nsi.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 16.1 203

`timescale 1 ps / 1 ps
module ghrd_10as066n2_altera_mm_interconnect_161_5qx5nsi (
		input  wire [3:0]  arria10_hps_h2f_axi_master_awid,                                        //                                       arria10_hps_h2f_axi_master.awid
		input  wire [31:0] arria10_hps_h2f_axi_master_awaddr,                                      //                                                                 .awaddr
		input  wire [3:0]  arria10_hps_h2f_axi_master_awlen,                                       //                                                                 .awlen
		input  wire [2:0]  arria10_hps_h2f_axi_master_awsize,                                      //                                                                 .awsize
		input  wire [1:0]  arria10_hps_h2f_axi_master_awburst,                                     //                                                                 .awburst
		input  wire [1:0]  arria10_hps_h2f_axi_master_awlock,                                      //                                                                 .awlock
		input  wire [3:0]  arria10_hps_h2f_axi_master_awcache,                                     //                                                                 .awcache
		input  wire [2:0]  arria10_hps_h2f_axi_master_awprot,                                      //                                                                 .awprot
		input  wire [4:0]  arria10_hps_h2f_axi_master_awuser,                                      //                                                                 .awuser
		input  wire        arria10_hps_h2f_axi_master_awvalid,                                     //                                                                 .awvalid
		output wire        arria10_hps_h2f_axi_master_awready,                                     //                                                                 .awready
		input  wire [3:0]  arria10_hps_h2f_axi_master_wid,                                         //                                                                 .wid
		input  wire [63:0] arria10_hps_h2f_axi_master_wdata,                                       //                                                                 .wdata
		input  wire [7:0]  arria10_hps_h2f_axi_master_wstrb,                                       //                                                                 .wstrb
		input  wire        arria10_hps_h2f_axi_master_wlast,                                       //                                                                 .wlast
		input  wire        arria10_hps_h2f_axi_master_wvalid,                                      //                                                                 .wvalid
		output wire        arria10_hps_h2f_axi_master_wready,                                      //                                                                 .wready
		output wire [3:0]  arria10_hps_h2f_axi_master_bid,                                         //                                                                 .bid
		output wire [1:0]  arria10_hps_h2f_axi_master_bresp,                                       //                                                                 .bresp
		output wire        arria10_hps_h2f_axi_master_bvalid,                                      //                                                                 .bvalid
		input  wire        arria10_hps_h2f_axi_master_bready,                                      //                                                                 .bready
		input  wire [3:0]  arria10_hps_h2f_axi_master_arid,                                        //                                                                 .arid
		input  wire [31:0] arria10_hps_h2f_axi_master_araddr,                                      //                                                                 .araddr
		input  wire [3:0]  arria10_hps_h2f_axi_master_arlen,                                       //                                                                 .arlen
		input  wire [2:0]  arria10_hps_h2f_axi_master_arsize,                                      //                                                                 .arsize
		input  wire [1:0]  arria10_hps_h2f_axi_master_arburst,                                     //                                                                 .arburst
		input  wire [1:0]  arria10_hps_h2f_axi_master_arlock,                                      //                                                                 .arlock
		input  wire [3:0]  arria10_hps_h2f_axi_master_arcache,                                     //                                                                 .arcache
		input  wire [2:0]  arria10_hps_h2f_axi_master_arprot,                                      //                                                                 .arprot
		input  wire [4:0]  arria10_hps_h2f_axi_master_aruser,                                      //                                                                 .aruser
		input  wire        arria10_hps_h2f_axi_master_arvalid,                                     //                                                                 .arvalid
		output wire        arria10_hps_h2f_axi_master_arready,                                     //                                                                 .arready
		output wire [3:0]  arria10_hps_h2f_axi_master_rid,                                         //                                                                 .rid
		output wire [63:0] arria10_hps_h2f_axi_master_rdata,                                       //                                                                 .rdata
		output wire [1:0]  arria10_hps_h2f_axi_master_rresp,                                       //                                                                 .rresp
		output wire        arria10_hps_h2f_axi_master_rlast,                                       //                                                                 .rlast
		output wire        arria10_hps_h2f_axi_master_rvalid,                                      //                                                                 .rvalid
		input  wire        arria10_hps_h2f_axi_master_rready,                                      //                                                                 .rready
		input  wire        clk_0_clk_clk,                                                          //                                                        clk_0_clk.clk
		input  wire        arria10_hps_h2f_axi_master_agent_clk_reset_reset_bridge_in_reset_reset, // arria10_hps_h2f_axi_master_agent_clk_reset_reset_bridge_in_reset.reset
		input  wire        sys_inti_mem_reset1_reset_bridge_in_reset_reset,                        //                        sys_inti_mem_reset1_reset_bridge_in_reset.reset
		output wire [17:0] sys_inti_mem_s1_address,                                                //                                                  sys_inti_mem_s1.address
		output wire        sys_inti_mem_s1_write,                                                  //                                                                 .write
		input  wire [7:0]  sys_inti_mem_s1_readdata,                                               //                                                                 .readdata
		output wire [7:0]  sys_inti_mem_s1_writedata,                                              //                                                                 .writedata
		output wire        sys_inti_mem_s1_chipselect,                                             //                                                                 .chipselect
		output wire        sys_inti_mem_s1_clken                                                   //                                                                 .clken
	);

	wire          rsp_mux_src_valid;                                       // rsp_mux:src_valid -> arria10_hps_h2f_axi_master_agent:write_rp_valid
	wire  [156:0] rsp_mux_src_data;                                        // rsp_mux:src_data -> arria10_hps_h2f_axi_master_agent:write_rp_data
	wire          rsp_mux_src_ready;                                       // arria10_hps_h2f_axi_master_agent:write_rp_ready -> rsp_mux:src_ready
	wire    [1:0] rsp_mux_src_channel;                                     // rsp_mux:src_channel -> arria10_hps_h2f_axi_master_agent:write_rp_channel
	wire          rsp_mux_src_startofpacket;                               // rsp_mux:src_startofpacket -> arria10_hps_h2f_axi_master_agent:write_rp_startofpacket
	wire          rsp_mux_src_endofpacket;                                 // rsp_mux:src_endofpacket -> arria10_hps_h2f_axi_master_agent:write_rp_endofpacket
	wire          rsp_mux_001_src_valid;                                   // rsp_mux_001:src_valid -> arria10_hps_h2f_axi_master_agent:read_rp_valid
	wire  [156:0] rsp_mux_001_src_data;                                    // rsp_mux_001:src_data -> arria10_hps_h2f_axi_master_agent:read_rp_data
	wire          rsp_mux_001_src_ready;                                   // arria10_hps_h2f_axi_master_agent:read_rp_ready -> rsp_mux_001:src_ready
	wire    [1:0] rsp_mux_001_src_channel;                                 // rsp_mux_001:src_channel -> arria10_hps_h2f_axi_master_agent:read_rp_channel
	wire          rsp_mux_001_src_startofpacket;                           // rsp_mux_001:src_startofpacket -> arria10_hps_h2f_axi_master_agent:read_rp_startofpacket
	wire          rsp_mux_001_src_endofpacket;                             // rsp_mux_001:src_endofpacket -> arria10_hps_h2f_axi_master_agent:read_rp_endofpacket
	wire    [7:0] sys_inti_mem_s1_agent_m0_readdata;                       // sys_inti_mem_s1_translator:uav_readdata -> sys_inti_mem_s1_agent:m0_readdata
	wire          sys_inti_mem_s1_agent_m0_waitrequest;                    // sys_inti_mem_s1_translator:uav_waitrequest -> sys_inti_mem_s1_agent:m0_waitrequest
	wire          sys_inti_mem_s1_agent_m0_debugaccess;                    // sys_inti_mem_s1_agent:m0_debugaccess -> sys_inti_mem_s1_translator:uav_debugaccess
	wire   [31:0] sys_inti_mem_s1_agent_m0_address;                        // sys_inti_mem_s1_agent:m0_address -> sys_inti_mem_s1_translator:uav_address
	wire    [0:0] sys_inti_mem_s1_agent_m0_byteenable;                     // sys_inti_mem_s1_agent:m0_byteenable -> sys_inti_mem_s1_translator:uav_byteenable
	wire          sys_inti_mem_s1_agent_m0_read;                           // sys_inti_mem_s1_agent:m0_read -> sys_inti_mem_s1_translator:uav_read
	wire          sys_inti_mem_s1_agent_m0_readdatavalid;                  // sys_inti_mem_s1_translator:uav_readdatavalid -> sys_inti_mem_s1_agent:m0_readdatavalid
	wire          sys_inti_mem_s1_agent_m0_lock;                           // sys_inti_mem_s1_agent:m0_lock -> sys_inti_mem_s1_translator:uav_lock
	wire    [7:0] sys_inti_mem_s1_agent_m0_writedata;                      // sys_inti_mem_s1_agent:m0_writedata -> sys_inti_mem_s1_translator:uav_writedata
	wire          sys_inti_mem_s1_agent_m0_write;                          // sys_inti_mem_s1_agent:m0_write -> sys_inti_mem_s1_translator:uav_write
	wire    [0:0] sys_inti_mem_s1_agent_m0_burstcount;                     // sys_inti_mem_s1_agent:m0_burstcount -> sys_inti_mem_s1_translator:uav_burstcount
	wire          sys_inti_mem_s1_agent_rf_source_valid;                   // sys_inti_mem_s1_agent:rf_source_valid -> sys_inti_mem_s1_agent_rsp_fifo:in_valid
	wire   [94:0] sys_inti_mem_s1_agent_rf_source_data;                    // sys_inti_mem_s1_agent:rf_source_data -> sys_inti_mem_s1_agent_rsp_fifo:in_data
	wire          sys_inti_mem_s1_agent_rf_source_ready;                   // sys_inti_mem_s1_agent_rsp_fifo:in_ready -> sys_inti_mem_s1_agent:rf_source_ready
	wire          sys_inti_mem_s1_agent_rf_source_startofpacket;           // sys_inti_mem_s1_agent:rf_source_startofpacket -> sys_inti_mem_s1_agent_rsp_fifo:in_startofpacket
	wire          sys_inti_mem_s1_agent_rf_source_endofpacket;             // sys_inti_mem_s1_agent:rf_source_endofpacket -> sys_inti_mem_s1_agent_rsp_fifo:in_endofpacket
	wire          sys_inti_mem_s1_agent_rsp_fifo_out_valid;                // sys_inti_mem_s1_agent_rsp_fifo:out_valid -> sys_inti_mem_s1_agent:rf_sink_valid
	wire   [94:0] sys_inti_mem_s1_agent_rsp_fifo_out_data;                 // sys_inti_mem_s1_agent_rsp_fifo:out_data -> sys_inti_mem_s1_agent:rf_sink_data
	wire          sys_inti_mem_s1_agent_rsp_fifo_out_ready;                // sys_inti_mem_s1_agent:rf_sink_ready -> sys_inti_mem_s1_agent_rsp_fifo:out_ready
	wire          sys_inti_mem_s1_agent_rsp_fifo_out_startofpacket;        // sys_inti_mem_s1_agent_rsp_fifo:out_startofpacket -> sys_inti_mem_s1_agent:rf_sink_startofpacket
	wire          sys_inti_mem_s1_agent_rsp_fifo_out_endofpacket;          // sys_inti_mem_s1_agent_rsp_fifo:out_endofpacket -> sys_inti_mem_s1_agent:rf_sink_endofpacket
	wire          sys_inti_mem_s1_agent_rdata_fifo_src_valid;              // sys_inti_mem_s1_agent:rdata_fifo_src_valid -> sys_inti_mem_s1_agent_rdata_fifo:in_valid
	wire    [9:0] sys_inti_mem_s1_agent_rdata_fifo_src_data;               // sys_inti_mem_s1_agent:rdata_fifo_src_data -> sys_inti_mem_s1_agent_rdata_fifo:in_data
	wire          sys_inti_mem_s1_agent_rdata_fifo_src_ready;              // sys_inti_mem_s1_agent_rdata_fifo:in_ready -> sys_inti_mem_s1_agent:rdata_fifo_src_ready
	wire          arria10_hps_h2f_axi_master_agent_write_cp_valid;         // arria10_hps_h2f_axi_master_agent:write_cp_valid -> router:sink_valid
	wire  [156:0] arria10_hps_h2f_axi_master_agent_write_cp_data;          // arria10_hps_h2f_axi_master_agent:write_cp_data -> router:sink_data
	wire          arria10_hps_h2f_axi_master_agent_write_cp_ready;         // router:sink_ready -> arria10_hps_h2f_axi_master_agent:write_cp_ready
	wire          arria10_hps_h2f_axi_master_agent_write_cp_startofpacket; // arria10_hps_h2f_axi_master_agent:write_cp_startofpacket -> router:sink_startofpacket
	wire          arria10_hps_h2f_axi_master_agent_write_cp_endofpacket;   // arria10_hps_h2f_axi_master_agent:write_cp_endofpacket -> router:sink_endofpacket
	wire          router_src_valid;                                        // router:src_valid -> cmd_demux:sink_valid
	wire  [156:0] router_src_data;                                         // router:src_data -> cmd_demux:sink_data
	wire          router_src_ready;                                        // cmd_demux:sink_ready -> router:src_ready
	wire    [1:0] router_src_channel;                                      // router:src_channel -> cmd_demux:sink_channel
	wire          router_src_startofpacket;                                // router:src_startofpacket -> cmd_demux:sink_startofpacket
	wire          router_src_endofpacket;                                  // router:src_endofpacket -> cmd_demux:sink_endofpacket
	wire          arria10_hps_h2f_axi_master_agent_read_cp_valid;          // arria10_hps_h2f_axi_master_agent:read_cp_valid -> router_001:sink_valid
	wire  [156:0] arria10_hps_h2f_axi_master_agent_read_cp_data;           // arria10_hps_h2f_axi_master_agent:read_cp_data -> router_001:sink_data
	wire          arria10_hps_h2f_axi_master_agent_read_cp_ready;          // router_001:sink_ready -> arria10_hps_h2f_axi_master_agent:read_cp_ready
	wire          arria10_hps_h2f_axi_master_agent_read_cp_startofpacket;  // arria10_hps_h2f_axi_master_agent:read_cp_startofpacket -> router_001:sink_startofpacket
	wire          arria10_hps_h2f_axi_master_agent_read_cp_endofpacket;    // arria10_hps_h2f_axi_master_agent:read_cp_endofpacket -> router_001:sink_endofpacket
	wire          router_001_src_valid;                                    // router_001:src_valid -> cmd_demux_001:sink_valid
	wire  [156:0] router_001_src_data;                                     // router_001:src_data -> cmd_demux_001:sink_data
	wire          router_001_src_ready;                                    // cmd_demux_001:sink_ready -> router_001:src_ready
	wire    [1:0] router_001_src_channel;                                  // router_001:src_channel -> cmd_demux_001:sink_channel
	wire          router_001_src_startofpacket;                            // router_001:src_startofpacket -> cmd_demux_001:sink_startofpacket
	wire          router_001_src_endofpacket;                              // router_001:src_endofpacket -> cmd_demux_001:sink_endofpacket
	wire          router_002_src_valid;                                    // router_002:src_valid -> sys_inti_mem_s1_rsp_width_adapter:in_valid
	wire   [93:0] router_002_src_data;                                     // router_002:src_data -> sys_inti_mem_s1_rsp_width_adapter:in_data
	wire          router_002_src_ready;                                    // sys_inti_mem_s1_rsp_width_adapter:in_ready -> router_002:src_ready
	wire    [1:0] router_002_src_channel;                                  // router_002:src_channel -> sys_inti_mem_s1_rsp_width_adapter:in_channel
	wire          router_002_src_startofpacket;                            // router_002:src_startofpacket -> sys_inti_mem_s1_rsp_width_adapter:in_startofpacket
	wire          router_002_src_endofpacket;                              // router_002:src_endofpacket -> sys_inti_mem_s1_rsp_width_adapter:in_endofpacket
	wire          sys_inti_mem_s1_rsp_width_adapter_src_valid;             // sys_inti_mem_s1_rsp_width_adapter:out_valid -> rsp_demux:sink_valid
	wire  [156:0] sys_inti_mem_s1_rsp_width_adapter_src_data;              // sys_inti_mem_s1_rsp_width_adapter:out_data -> rsp_demux:sink_data
	wire          sys_inti_mem_s1_rsp_width_adapter_src_ready;             // rsp_demux:sink_ready -> sys_inti_mem_s1_rsp_width_adapter:out_ready
	wire    [1:0] sys_inti_mem_s1_rsp_width_adapter_src_channel;           // sys_inti_mem_s1_rsp_width_adapter:out_channel -> rsp_demux:sink_channel
	wire          sys_inti_mem_s1_rsp_width_adapter_src_startofpacket;     // sys_inti_mem_s1_rsp_width_adapter:out_startofpacket -> rsp_demux:sink_startofpacket
	wire          sys_inti_mem_s1_rsp_width_adapter_src_endofpacket;       // sys_inti_mem_s1_rsp_width_adapter:out_endofpacket -> rsp_demux:sink_endofpacket
	wire          cmd_mux_src_valid;                                       // cmd_mux:src_valid -> sys_inti_mem_s1_cmd_width_adapter:in_valid
	wire  [156:0] cmd_mux_src_data;                                        // cmd_mux:src_data -> sys_inti_mem_s1_cmd_width_adapter:in_data
	wire          cmd_mux_src_ready;                                       // sys_inti_mem_s1_cmd_width_adapter:in_ready -> cmd_mux:src_ready
	wire    [1:0] cmd_mux_src_channel;                                     // cmd_mux:src_channel -> sys_inti_mem_s1_cmd_width_adapter:in_channel
	wire          cmd_mux_src_startofpacket;                               // cmd_mux:src_startofpacket -> sys_inti_mem_s1_cmd_width_adapter:in_startofpacket
	wire          cmd_mux_src_endofpacket;                                 // cmd_mux:src_endofpacket -> sys_inti_mem_s1_cmd_width_adapter:in_endofpacket
	wire          sys_inti_mem_s1_cmd_width_adapter_src_valid;             // sys_inti_mem_s1_cmd_width_adapter:out_valid -> sys_inti_mem_s1_burst_adapter:sink0_valid
	wire   [93:0] sys_inti_mem_s1_cmd_width_adapter_src_data;              // sys_inti_mem_s1_cmd_width_adapter:out_data -> sys_inti_mem_s1_burst_adapter:sink0_data
	wire          sys_inti_mem_s1_cmd_width_adapter_src_ready;             // sys_inti_mem_s1_burst_adapter:sink0_ready -> sys_inti_mem_s1_cmd_width_adapter:out_ready
	wire    [1:0] sys_inti_mem_s1_cmd_width_adapter_src_channel;           // sys_inti_mem_s1_cmd_width_adapter:out_channel -> sys_inti_mem_s1_burst_adapter:sink0_channel
	wire          sys_inti_mem_s1_cmd_width_adapter_src_startofpacket;     // sys_inti_mem_s1_cmd_width_adapter:out_startofpacket -> sys_inti_mem_s1_burst_adapter:sink0_startofpacket
	wire          sys_inti_mem_s1_cmd_width_adapter_src_endofpacket;       // sys_inti_mem_s1_cmd_width_adapter:out_endofpacket -> sys_inti_mem_s1_burst_adapter:sink0_endofpacket
	wire          sys_inti_mem_s1_burst_adapter_source0_valid;             // sys_inti_mem_s1_burst_adapter:source0_valid -> agent_pipeline:in_valid
	wire   [93:0] sys_inti_mem_s1_burst_adapter_source0_data;              // sys_inti_mem_s1_burst_adapter:source0_data -> agent_pipeline:in_data
	wire          sys_inti_mem_s1_burst_adapter_source0_ready;             // agent_pipeline:in_ready -> sys_inti_mem_s1_burst_adapter:source0_ready
	wire    [1:0] sys_inti_mem_s1_burst_adapter_source0_channel;           // sys_inti_mem_s1_burst_adapter:source0_channel -> agent_pipeline:in_channel
	wire          sys_inti_mem_s1_burst_adapter_source0_startofpacket;     // sys_inti_mem_s1_burst_adapter:source0_startofpacket -> agent_pipeline:in_startofpacket
	wire          sys_inti_mem_s1_burst_adapter_source0_endofpacket;       // sys_inti_mem_s1_burst_adapter:source0_endofpacket -> agent_pipeline:in_endofpacket
	wire          agent_pipeline_source0_valid;                            // agent_pipeline:out_valid -> sys_inti_mem_s1_agent:cp_valid
	wire   [93:0] agent_pipeline_source0_data;                             // agent_pipeline:out_data -> sys_inti_mem_s1_agent:cp_data
	wire          agent_pipeline_source0_ready;                            // sys_inti_mem_s1_agent:cp_ready -> agent_pipeline:out_ready
	wire    [1:0] agent_pipeline_source0_channel;                          // agent_pipeline:out_channel -> sys_inti_mem_s1_agent:cp_channel
	wire          agent_pipeline_source0_startofpacket;                    // agent_pipeline:out_startofpacket -> sys_inti_mem_s1_agent:cp_startofpacket
	wire          agent_pipeline_source0_endofpacket;                      // agent_pipeline:out_endofpacket -> sys_inti_mem_s1_agent:cp_endofpacket
	wire          sys_inti_mem_s1_agent_rp_valid;                          // sys_inti_mem_s1_agent:rp_valid -> agent_pipeline_001:in_valid
	wire   [93:0] sys_inti_mem_s1_agent_rp_data;                           // sys_inti_mem_s1_agent:rp_data -> agent_pipeline_001:in_data
	wire          sys_inti_mem_s1_agent_rp_ready;                          // agent_pipeline_001:in_ready -> sys_inti_mem_s1_agent:rp_ready
	wire          sys_inti_mem_s1_agent_rp_startofpacket;                  // sys_inti_mem_s1_agent:rp_startofpacket -> agent_pipeline_001:in_startofpacket
	wire          sys_inti_mem_s1_agent_rp_endofpacket;                    // sys_inti_mem_s1_agent:rp_endofpacket -> agent_pipeline_001:in_endofpacket
	wire          agent_pipeline_001_source0_valid;                        // agent_pipeline_001:out_valid -> router_002:sink_valid
	wire   [93:0] agent_pipeline_001_source0_data;                         // agent_pipeline_001:out_data -> router_002:sink_data
	wire          agent_pipeline_001_source0_ready;                        // router_002:sink_ready -> agent_pipeline_001:out_ready
	wire          agent_pipeline_001_source0_startofpacket;                // agent_pipeline_001:out_startofpacket -> router_002:sink_startofpacket
	wire          agent_pipeline_001_source0_endofpacket;                  // agent_pipeline_001:out_endofpacket -> router_002:sink_endofpacket
	wire          cmd_demux_src0_valid;                                    // cmd_demux:src0_valid -> mux_pipeline:in_valid
	wire  [156:0] cmd_demux_src0_data;                                     // cmd_demux:src0_data -> mux_pipeline:in_data
	wire          cmd_demux_src0_ready;                                    // mux_pipeline:in_ready -> cmd_demux:src0_ready
	wire    [1:0] cmd_demux_src0_channel;                                  // cmd_demux:src0_channel -> mux_pipeline:in_channel
	wire          cmd_demux_src0_startofpacket;                            // cmd_demux:src0_startofpacket -> mux_pipeline:in_startofpacket
	wire          cmd_demux_src0_endofpacket;                              // cmd_demux:src0_endofpacket -> mux_pipeline:in_endofpacket
	wire          mux_pipeline_source0_valid;                              // mux_pipeline:out_valid -> cmd_mux:sink0_valid
	wire  [156:0] mux_pipeline_source0_data;                               // mux_pipeline:out_data -> cmd_mux:sink0_data
	wire          mux_pipeline_source0_ready;                              // cmd_mux:sink0_ready -> mux_pipeline:out_ready
	wire    [1:0] mux_pipeline_source0_channel;                            // mux_pipeline:out_channel -> cmd_mux:sink0_channel
	wire          mux_pipeline_source0_startofpacket;                      // mux_pipeline:out_startofpacket -> cmd_mux:sink0_startofpacket
	wire          mux_pipeline_source0_endofpacket;                        // mux_pipeline:out_endofpacket -> cmd_mux:sink0_endofpacket
	wire          cmd_demux_001_src0_valid;                                // cmd_demux_001:src0_valid -> mux_pipeline_001:in_valid
	wire  [156:0] cmd_demux_001_src0_data;                                 // cmd_demux_001:src0_data -> mux_pipeline_001:in_data
	wire          cmd_demux_001_src0_ready;                                // mux_pipeline_001:in_ready -> cmd_demux_001:src0_ready
	wire    [1:0] cmd_demux_001_src0_channel;                              // cmd_demux_001:src0_channel -> mux_pipeline_001:in_channel
	wire          cmd_demux_001_src0_startofpacket;                        // cmd_demux_001:src0_startofpacket -> mux_pipeline_001:in_startofpacket
	wire          cmd_demux_001_src0_endofpacket;                          // cmd_demux_001:src0_endofpacket -> mux_pipeline_001:in_endofpacket
	wire          mux_pipeline_001_source0_valid;                          // mux_pipeline_001:out_valid -> cmd_mux:sink1_valid
	wire  [156:0] mux_pipeline_001_source0_data;                           // mux_pipeline_001:out_data -> cmd_mux:sink1_data
	wire          mux_pipeline_001_source0_ready;                          // cmd_mux:sink1_ready -> mux_pipeline_001:out_ready
	wire    [1:0] mux_pipeline_001_source0_channel;                        // mux_pipeline_001:out_channel -> cmd_mux:sink1_channel
	wire          mux_pipeline_001_source0_startofpacket;                  // mux_pipeline_001:out_startofpacket -> cmd_mux:sink1_startofpacket
	wire          mux_pipeline_001_source0_endofpacket;                    // mux_pipeline_001:out_endofpacket -> cmd_mux:sink1_endofpacket
	wire          rsp_demux_src0_valid;                                    // rsp_demux:src0_valid -> mux_pipeline_002:in_valid
	wire  [156:0] rsp_demux_src0_data;                                     // rsp_demux:src0_data -> mux_pipeline_002:in_data
	wire          rsp_demux_src0_ready;                                    // mux_pipeline_002:in_ready -> rsp_demux:src0_ready
	wire    [1:0] rsp_demux_src0_channel;                                  // rsp_demux:src0_channel -> mux_pipeline_002:in_channel
	wire          rsp_demux_src0_startofpacket;                            // rsp_demux:src0_startofpacket -> mux_pipeline_002:in_startofpacket
	wire          rsp_demux_src0_endofpacket;                              // rsp_demux:src0_endofpacket -> mux_pipeline_002:in_endofpacket
	wire          mux_pipeline_002_source0_valid;                          // mux_pipeline_002:out_valid -> rsp_mux:sink0_valid
	wire  [156:0] mux_pipeline_002_source0_data;                           // mux_pipeline_002:out_data -> rsp_mux:sink0_data
	wire          mux_pipeline_002_source0_ready;                          // rsp_mux:sink0_ready -> mux_pipeline_002:out_ready
	wire    [1:0] mux_pipeline_002_source0_channel;                        // mux_pipeline_002:out_channel -> rsp_mux:sink0_channel
	wire          mux_pipeline_002_source0_startofpacket;                  // mux_pipeline_002:out_startofpacket -> rsp_mux:sink0_startofpacket
	wire          mux_pipeline_002_source0_endofpacket;                    // mux_pipeline_002:out_endofpacket -> rsp_mux:sink0_endofpacket
	wire          rsp_demux_src1_valid;                                    // rsp_demux:src1_valid -> mux_pipeline_003:in_valid
	wire  [156:0] rsp_demux_src1_data;                                     // rsp_demux:src1_data -> mux_pipeline_003:in_data
	wire          rsp_demux_src1_ready;                                    // mux_pipeline_003:in_ready -> rsp_demux:src1_ready
	wire    [1:0] rsp_demux_src1_channel;                                  // rsp_demux:src1_channel -> mux_pipeline_003:in_channel
	wire          rsp_demux_src1_startofpacket;                            // rsp_demux:src1_startofpacket -> mux_pipeline_003:in_startofpacket
	wire          rsp_demux_src1_endofpacket;                              // rsp_demux:src1_endofpacket -> mux_pipeline_003:in_endofpacket
	wire          mux_pipeline_003_source0_valid;                          // mux_pipeline_003:out_valid -> rsp_mux_001:sink0_valid
	wire  [156:0] mux_pipeline_003_source0_data;                           // mux_pipeline_003:out_data -> rsp_mux_001:sink0_data
	wire          mux_pipeline_003_source0_ready;                          // rsp_mux_001:sink0_ready -> mux_pipeline_003:out_ready
	wire    [1:0] mux_pipeline_003_source0_channel;                        // mux_pipeline_003:out_channel -> rsp_mux_001:sink0_channel
	wire          mux_pipeline_003_source0_startofpacket;                  // mux_pipeline_003:out_startofpacket -> rsp_mux_001:sink0_startofpacket
	wire          mux_pipeline_003_source0_endofpacket;                    // mux_pipeline_003:out_endofpacket -> rsp_mux_001:sink0_endofpacket
	wire          sys_inti_mem_s1_agent_rdata_fifo_out_valid;              // sys_inti_mem_s1_agent_rdata_fifo:out_valid -> avalon_st_adapter:in_0_valid
	wire    [9:0] sys_inti_mem_s1_agent_rdata_fifo_out_data;               // sys_inti_mem_s1_agent_rdata_fifo:out_data -> avalon_st_adapter:in_0_data
	wire          sys_inti_mem_s1_agent_rdata_fifo_out_ready;              // avalon_st_adapter:in_0_ready -> sys_inti_mem_s1_agent_rdata_fifo:out_ready
	wire          avalon_st_adapter_out_0_valid;                           // avalon_st_adapter:out_0_valid -> sys_inti_mem_s1_agent:rdata_fifo_sink_valid
	wire    [9:0] avalon_st_adapter_out_0_data;                            // avalon_st_adapter:out_0_data -> sys_inti_mem_s1_agent:rdata_fifo_sink_data
	wire          avalon_st_adapter_out_0_ready;                           // sys_inti_mem_s1_agent:rdata_fifo_sink_ready -> avalon_st_adapter:out_0_ready
	wire    [0:0] avalon_st_adapter_out_0_error;                           // avalon_st_adapter:out_0_error -> sys_inti_mem_s1_agent:rdata_fifo_sink_error

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (18),
		.AV_DATA_W                      (8),
		.UAV_DATA_W                     (8),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (1),
		.UAV_BYTEENABLE_W               (1),
		.UAV_ADDRESS_W                  (32),
		.UAV_BURSTCOUNT_W               (1),
		.AV_READLATENCY                 (1),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (1),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) sys_inti_mem_s1_translator (
		.clk                    (clk_0_clk_clk),                                   //                      clk.clk
		.reset                  (sys_inti_mem_reset1_reset_bridge_in_reset_reset), //                    reset.reset
		.uav_address            (sys_inti_mem_s1_agent_m0_address),                // avalon_universal_slave_0.address
		.uav_burstcount         (sys_inti_mem_s1_agent_m0_burstcount),             //                         .burstcount
		.uav_read               (sys_inti_mem_s1_agent_m0_read),                   //                         .read
		.uav_write              (sys_inti_mem_s1_agent_m0_write),                  //                         .write
		.uav_waitrequest        (sys_inti_mem_s1_agent_m0_waitrequest),            //                         .waitrequest
		.uav_readdatavalid      (sys_inti_mem_s1_agent_m0_readdatavalid),          //                         .readdatavalid
		.uav_byteenable         (sys_inti_mem_s1_agent_m0_byteenable),             //                         .byteenable
		.uav_readdata           (sys_inti_mem_s1_agent_m0_readdata),               //                         .readdata
		.uav_writedata          (sys_inti_mem_s1_agent_m0_writedata),              //                         .writedata
		.uav_lock               (sys_inti_mem_s1_agent_m0_lock),                   //                         .lock
		.uav_debugaccess        (sys_inti_mem_s1_agent_m0_debugaccess),            //                         .debugaccess
		.av_address             (sys_inti_mem_s1_address),                         //      avalon_anti_slave_0.address
		.av_write               (sys_inti_mem_s1_write),                           //                         .write
		.av_readdata            (sys_inti_mem_s1_readdata),                        //                         .readdata
		.av_writedata           (sys_inti_mem_s1_writedata),                       //                         .writedata
		.av_chipselect          (sys_inti_mem_s1_chipselect),                      //                         .chipselect
		.av_clken               (sys_inti_mem_s1_clken),                           //                         .clken
		.av_read                (),                                                //              (terminated)
		.av_begintransfer       (),                                                //              (terminated)
		.av_beginbursttransfer  (),                                                //              (terminated)
		.av_burstcount          (),                                                //              (terminated)
		.av_byteenable          (),                                                //              (terminated)
		.av_readdatavalid       (1'b0),                                            //              (terminated)
		.av_waitrequest         (1'b0),                                            //              (terminated)
		.av_writebyteenable     (),                                                //              (terminated)
		.av_lock                (),                                                //              (terminated)
		.uav_clken              (1'b0),                                            //              (terminated)
		.av_debugaccess         (),                                                //              (terminated)
		.av_outputenable        (),                                                //              (terminated)
		.uav_response           (),                                                //              (terminated)
		.av_response            (2'b00),                                           //              (terminated)
		.uav_writeresponsevalid (),                                                //              (terminated)
		.av_writeresponsevalid  (1'b0)                                             //              (terminated)
	);

	altera_merlin_axi_master_ni #(
		.ID_WIDTH                  (4),
		.ADDR_WIDTH                (32),
		.RDATA_WIDTH               (64),
		.WDATA_WIDTH               (64),
		.ADDR_USER_WIDTH           (5),
		.DATA_USER_WIDTH           (1),
		.AXI_BURST_LENGTH_WIDTH    (4),
		.AXI_LOCK_WIDTH            (2),
		.AXI_VERSION               ("AXI3"),
		.WRITE_ISSUING_CAPABILITY  (8),
		.READ_ISSUING_CAPABILITY   (8),
		.PKT_BEGIN_BURST           (137),
		.PKT_CACHE_H               (151),
		.PKT_CACHE_L               (148),
		.PKT_ADDR_SIDEBAND_H       (135),
		.PKT_ADDR_SIDEBAND_L       (131),
		.PKT_PROTECTION_H          (147),
		.PKT_PROTECTION_L          (145),
		.PKT_BURST_SIZE_H          (128),
		.PKT_BURST_SIZE_L          (126),
		.PKT_BURST_TYPE_H          (130),
		.PKT_BURST_TYPE_L          (129),
		.PKT_RESPONSE_STATUS_L     (152),
		.PKT_RESPONSE_STATUS_H     (153),
		.PKT_BURSTWRAP_H           (125),
		.PKT_BURSTWRAP_L           (118),
		.PKT_BYTE_CNT_H            (117),
		.PKT_BYTE_CNT_L            (110),
		.PKT_ADDR_H                (103),
		.PKT_ADDR_L                (72),
		.PKT_TRANS_EXCLUSIVE       (109),
		.PKT_TRANS_LOCK            (108),
		.PKT_TRANS_COMPRESSED_READ (104),
		.PKT_TRANS_POSTED          (105),
		.PKT_TRANS_WRITE           (106),
		.PKT_TRANS_READ            (107),
		.PKT_DATA_H                (63),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (71),
		.PKT_BYTEEN_L              (64),
		.PKT_SRC_ID_H              (139),
		.PKT_SRC_ID_L              (139),
		.PKT_DEST_ID_H             (140),
		.PKT_DEST_ID_L             (140),
		.PKT_THREAD_ID_H           (144),
		.PKT_THREAD_ID_L           (141),
		.PKT_QOS_L                 (138),
		.PKT_QOS_H                 (138),
		.PKT_ORI_BURST_SIZE_L      (154),
		.PKT_ORI_BURST_SIZE_H      (156),
		.PKT_DATA_SIDEBAND_H       (136),
		.PKT_DATA_SIDEBAND_L       (136),
		.ST_DATA_W                 (157),
		.ST_CHANNEL_W              (2),
		.ID                        (0)
	) arria10_hps_h2f_axi_master_agent (
		.aclk                   (clk_0_clk_clk),                                                           //              clk.clk
		.aresetn                (~arria10_hps_h2f_axi_master_agent_clk_reset_reset_bridge_in_reset_reset), //        clk_reset.reset_n
		.write_cp_valid         (arria10_hps_h2f_axi_master_agent_write_cp_valid),                         //         write_cp.valid
		.write_cp_data          (arria10_hps_h2f_axi_master_agent_write_cp_data),                          //                 .data
		.write_cp_startofpacket (arria10_hps_h2f_axi_master_agent_write_cp_startofpacket),                 //                 .startofpacket
		.write_cp_endofpacket   (arria10_hps_h2f_axi_master_agent_write_cp_endofpacket),                   //                 .endofpacket
		.write_cp_ready         (arria10_hps_h2f_axi_master_agent_write_cp_ready),                         //                 .ready
		.write_rp_valid         (rsp_mux_src_valid),                                                       //         write_rp.valid
		.write_rp_data          (rsp_mux_src_data),                                                        //                 .data
		.write_rp_channel       (rsp_mux_src_channel),                                                     //                 .channel
		.write_rp_startofpacket (rsp_mux_src_startofpacket),                                               //                 .startofpacket
		.write_rp_endofpacket   (rsp_mux_src_endofpacket),                                                 //                 .endofpacket
		.write_rp_ready         (rsp_mux_src_ready),                                                       //                 .ready
		.read_cp_valid          (arria10_hps_h2f_axi_master_agent_read_cp_valid),                          //          read_cp.valid
		.read_cp_data           (arria10_hps_h2f_axi_master_agent_read_cp_data),                           //                 .data
		.read_cp_startofpacket  (arria10_hps_h2f_axi_master_agent_read_cp_startofpacket),                  //                 .startofpacket
		.read_cp_endofpacket    (arria10_hps_h2f_axi_master_agent_read_cp_endofpacket),                    //                 .endofpacket
		.read_cp_ready          (arria10_hps_h2f_axi_master_agent_read_cp_ready),                          //                 .ready
		.read_rp_valid          (rsp_mux_001_src_valid),                                                   //          read_rp.valid
		.read_rp_data           (rsp_mux_001_src_data),                                                    //                 .data
		.read_rp_channel        (rsp_mux_001_src_channel),                                                 //                 .channel
		.read_rp_startofpacket  (rsp_mux_001_src_startofpacket),                                           //                 .startofpacket
		.read_rp_endofpacket    (rsp_mux_001_src_endofpacket),                                             //                 .endofpacket
		.read_rp_ready          (rsp_mux_001_src_ready),                                                   //                 .ready
		.awid                   (arria10_hps_h2f_axi_master_awid),                                         // altera_axi_slave.awid
		.awaddr                 (arria10_hps_h2f_axi_master_awaddr),                                       //                 .awaddr
		.awlen                  (arria10_hps_h2f_axi_master_awlen),                                        //                 .awlen
		.awsize                 (arria10_hps_h2f_axi_master_awsize),                                       //                 .awsize
		.awburst                (arria10_hps_h2f_axi_master_awburst),                                      //                 .awburst
		.awlock                 (arria10_hps_h2f_axi_master_awlock),                                       //                 .awlock
		.awcache                (arria10_hps_h2f_axi_master_awcache),                                      //                 .awcache
		.awprot                 (arria10_hps_h2f_axi_master_awprot),                                       //                 .awprot
		.awuser                 (arria10_hps_h2f_axi_master_awuser),                                       //                 .awuser
		.awvalid                (arria10_hps_h2f_axi_master_awvalid),                                      //                 .awvalid
		.awready                (arria10_hps_h2f_axi_master_awready),                                      //                 .awready
		.wid                    (arria10_hps_h2f_axi_master_wid),                                          //                 .wid
		.wdata                  (arria10_hps_h2f_axi_master_wdata),                                        //                 .wdata
		.wstrb                  (arria10_hps_h2f_axi_master_wstrb),                                        //                 .wstrb
		.wlast                  (arria10_hps_h2f_axi_master_wlast),                                        //                 .wlast
		.wvalid                 (arria10_hps_h2f_axi_master_wvalid),                                       //                 .wvalid
		.wready                 (arria10_hps_h2f_axi_master_wready),                                       //                 .wready
		.bid                    (arria10_hps_h2f_axi_master_bid),                                          //                 .bid
		.bresp                  (arria10_hps_h2f_axi_master_bresp),                                        //                 .bresp
		.bvalid                 (arria10_hps_h2f_axi_master_bvalid),                                       //                 .bvalid
		.bready                 (arria10_hps_h2f_axi_master_bready),                                       //                 .bready
		.arid                   (arria10_hps_h2f_axi_master_arid),                                         //                 .arid
		.araddr                 (arria10_hps_h2f_axi_master_araddr),                                       //                 .araddr
		.arlen                  (arria10_hps_h2f_axi_master_arlen),                                        //                 .arlen
		.arsize                 (arria10_hps_h2f_axi_master_arsize),                                       //                 .arsize
		.arburst                (arria10_hps_h2f_axi_master_arburst),                                      //                 .arburst
		.arlock                 (arria10_hps_h2f_axi_master_arlock),                                       //                 .arlock
		.arcache                (arria10_hps_h2f_axi_master_arcache),                                      //                 .arcache
		.arprot                 (arria10_hps_h2f_axi_master_arprot),                                       //                 .arprot
		.aruser                 (arria10_hps_h2f_axi_master_aruser),                                       //                 .aruser
		.arvalid                (arria10_hps_h2f_axi_master_arvalid),                                      //                 .arvalid
		.arready                (arria10_hps_h2f_axi_master_arready),                                      //                 .arready
		.rid                    (arria10_hps_h2f_axi_master_rid),                                          //                 .rid
		.rdata                  (arria10_hps_h2f_axi_master_rdata),                                        //                 .rdata
		.rresp                  (arria10_hps_h2f_axi_master_rresp),                                        //                 .rresp
		.rlast                  (arria10_hps_h2f_axi_master_rlast),                                        //                 .rlast
		.rvalid                 (arria10_hps_h2f_axi_master_rvalid),                                       //                 .rvalid
		.rready                 (arria10_hps_h2f_axi_master_rready),                                       //                 .rready
		.awqos                  (4'b0000),                                                                 //      (terminated)
		.arqos                  (4'b0000),                                                                 //      (terminated)
		.awregion               (4'b0000),                                                                 //      (terminated)
		.arregion               (4'b0000),                                                                 //      (terminated)
		.wuser                  (1'b0),                                                                    //      (terminated)
		.ruser                  (),                                                                        //      (terminated)
		.buser                  ()                                                                         //      (terminated)
	);

	altera_merlin_slave_agent #(
		.PKT_ORI_BURST_SIZE_H      (93),
		.PKT_ORI_BURST_SIZE_L      (91),
		.PKT_RESPONSE_STATUS_H     (90),
		.PKT_RESPONSE_STATUS_L     (89),
		.PKT_BURST_SIZE_H          (65),
		.PKT_BURST_SIZE_L          (63),
		.PKT_TRANS_LOCK            (45),
		.PKT_BEGIN_BURST           (74),
		.PKT_PROTECTION_H          (84),
		.PKT_PROTECTION_L          (82),
		.PKT_BURSTWRAP_H           (62),
		.PKT_BURSTWRAP_L           (55),
		.PKT_BYTE_CNT_H            (54),
		.PKT_BYTE_CNT_L            (47),
		.PKT_ADDR_H                (40),
		.PKT_ADDR_L                (9),
		.PKT_TRANS_COMPRESSED_READ (41),
		.PKT_TRANS_POSTED          (42),
		.PKT_TRANS_WRITE           (43),
		.PKT_TRANS_READ            (44),
		.PKT_DATA_H                (7),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (8),
		.PKT_BYTEEN_L              (8),
		.PKT_SRC_ID_H              (76),
		.PKT_SRC_ID_L              (76),
		.PKT_DEST_ID_H             (77),
		.PKT_DEST_ID_L             (77),
		.PKT_SYMBOL_W              (8),
		.ST_CHANNEL_W              (2),
		.ST_DATA_W                 (94),
		.AVS_BURSTCOUNT_W          (1),
		.SUPPRESS_0_BYTEEN_CMD     (1),
		.PREVENT_FIFO_OVERFLOW     (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0),
		.ECC_ENABLE                (0)
	) sys_inti_mem_s1_agent (
		.clk                     (clk_0_clk_clk),                                    //             clk.clk
		.reset                   (sys_inti_mem_reset1_reset_bridge_in_reset_reset),  //       clk_reset.reset
		.m0_address              (sys_inti_mem_s1_agent_m0_address),                 //              m0.address
		.m0_burstcount           (sys_inti_mem_s1_agent_m0_burstcount),              //                .burstcount
		.m0_byteenable           (sys_inti_mem_s1_agent_m0_byteenable),              //                .byteenable
		.m0_debugaccess          (sys_inti_mem_s1_agent_m0_debugaccess),             //                .debugaccess
		.m0_lock                 (sys_inti_mem_s1_agent_m0_lock),                    //                .lock
		.m0_readdata             (sys_inti_mem_s1_agent_m0_readdata),                //                .readdata
		.m0_readdatavalid        (sys_inti_mem_s1_agent_m0_readdatavalid),           //                .readdatavalid
		.m0_read                 (sys_inti_mem_s1_agent_m0_read),                    //                .read
		.m0_waitrequest          (sys_inti_mem_s1_agent_m0_waitrequest),             //                .waitrequest
		.m0_writedata            (sys_inti_mem_s1_agent_m0_writedata),               //                .writedata
		.m0_write                (sys_inti_mem_s1_agent_m0_write),                   //                .write
		.rp_endofpacket          (sys_inti_mem_s1_agent_rp_endofpacket),             //              rp.endofpacket
		.rp_ready                (sys_inti_mem_s1_agent_rp_ready),                   //                .ready
		.rp_valid                (sys_inti_mem_s1_agent_rp_valid),                   //                .valid
		.rp_data                 (sys_inti_mem_s1_agent_rp_data),                    //                .data
		.rp_startofpacket        (sys_inti_mem_s1_agent_rp_startofpacket),           //                .startofpacket
		.cp_ready                (agent_pipeline_source0_ready),                     //              cp.ready
		.cp_valid                (agent_pipeline_source0_valid),                     //                .valid
		.cp_data                 (agent_pipeline_source0_data),                      //                .data
		.cp_startofpacket        (agent_pipeline_source0_startofpacket),             //                .startofpacket
		.cp_endofpacket          (agent_pipeline_source0_endofpacket),               //                .endofpacket
		.cp_channel              (agent_pipeline_source0_channel),                   //                .channel
		.rf_sink_ready           (sys_inti_mem_s1_agent_rsp_fifo_out_ready),         //         rf_sink.ready
		.rf_sink_valid           (sys_inti_mem_s1_agent_rsp_fifo_out_valid),         //                .valid
		.rf_sink_startofpacket   (sys_inti_mem_s1_agent_rsp_fifo_out_startofpacket), //                .startofpacket
		.rf_sink_endofpacket     (sys_inti_mem_s1_agent_rsp_fifo_out_endofpacket),   //                .endofpacket
		.rf_sink_data            (sys_inti_mem_s1_agent_rsp_fifo_out_data),          //                .data
		.rf_source_ready         (sys_inti_mem_s1_agent_rf_source_ready),            //       rf_source.ready
		.rf_source_valid         (sys_inti_mem_s1_agent_rf_source_valid),            //                .valid
		.rf_source_startofpacket (sys_inti_mem_s1_agent_rf_source_startofpacket),    //                .startofpacket
		.rf_source_endofpacket   (sys_inti_mem_s1_agent_rf_source_endofpacket),      //                .endofpacket
		.rf_source_data          (sys_inti_mem_s1_agent_rf_source_data),             //                .data
		.rdata_fifo_sink_ready   (avalon_st_adapter_out_0_ready),                    // rdata_fifo_sink.ready
		.rdata_fifo_sink_valid   (avalon_st_adapter_out_0_valid),                    //                .valid
		.rdata_fifo_sink_data    (avalon_st_adapter_out_0_data),                     //                .data
		.rdata_fifo_sink_error   (avalon_st_adapter_out_0_error),                    //                .error
		.rdata_fifo_src_ready    (sys_inti_mem_s1_agent_rdata_fifo_src_ready),       //  rdata_fifo_src.ready
		.rdata_fifo_src_valid    (sys_inti_mem_s1_agent_rdata_fifo_src_valid),       //                .valid
		.rdata_fifo_src_data     (sys_inti_mem_s1_agent_rdata_fifo_src_data),        //                .data
		.m0_response             (2'b00),                                            //     (terminated)
		.m0_writeresponsevalid   (1'b0)                                              //     (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (95),
		.FIFO_DEPTH          (2),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (1),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) sys_inti_mem_s1_agent_rsp_fifo (
		.clk               (clk_0_clk_clk),                                    //       clk.clk
		.reset             (sys_inti_mem_reset1_reset_bridge_in_reset_reset),  // clk_reset.reset
		.in_data           (sys_inti_mem_s1_agent_rf_source_data),             //        in.data
		.in_valid          (sys_inti_mem_s1_agent_rf_source_valid),            //          .valid
		.in_ready          (sys_inti_mem_s1_agent_rf_source_ready),            //          .ready
		.in_startofpacket  (sys_inti_mem_s1_agent_rf_source_startofpacket),    //          .startofpacket
		.in_endofpacket    (sys_inti_mem_s1_agent_rf_source_endofpacket),      //          .endofpacket
		.out_data          (sys_inti_mem_s1_agent_rsp_fifo_out_data),          //       out.data
		.out_valid         (sys_inti_mem_s1_agent_rsp_fifo_out_valid),         //          .valid
		.out_ready         (sys_inti_mem_s1_agent_rsp_fifo_out_ready),         //          .ready
		.out_startofpacket (sys_inti_mem_s1_agent_rsp_fifo_out_startofpacket), //          .startofpacket
		.out_endofpacket   (sys_inti_mem_s1_agent_rsp_fifo_out_endofpacket),   //          .endofpacket
		.csr_address       (2'b00),                                            // (terminated)
		.csr_read          (1'b0),                                             // (terminated)
		.csr_write         (1'b0),                                             // (terminated)
		.csr_readdata      (),                                                 // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),             // (terminated)
		.almost_full_data  (),                                                 // (terminated)
		.almost_empty_data (),                                                 // (terminated)
		.in_empty          (1'b0),                                             // (terminated)
		.out_empty         (),                                                 // (terminated)
		.in_error          (1'b0),                                             // (terminated)
		.out_error         (),                                                 // (terminated)
		.in_channel        (1'b0),                                             // (terminated)
		.out_channel       ()                                                  // (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (10),
		.FIFO_DEPTH          (2),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (0),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (0),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) sys_inti_mem_s1_agent_rdata_fifo (
		.clk               (clk_0_clk_clk),                                   //       clk.clk
		.reset             (sys_inti_mem_reset1_reset_bridge_in_reset_reset), // clk_reset.reset
		.in_data           (sys_inti_mem_s1_agent_rdata_fifo_src_data),       //        in.data
		.in_valid          (sys_inti_mem_s1_agent_rdata_fifo_src_valid),      //          .valid
		.in_ready          (sys_inti_mem_s1_agent_rdata_fifo_src_ready),      //          .ready
		.out_data          (sys_inti_mem_s1_agent_rdata_fifo_out_data),       //       out.data
		.out_valid         (sys_inti_mem_s1_agent_rdata_fifo_out_valid),      //          .valid
		.out_ready         (sys_inti_mem_s1_agent_rdata_fifo_out_ready),      //          .ready
		.csr_address       (2'b00),                                           // (terminated)
		.csr_read          (1'b0),                                            // (terminated)
		.csr_write         (1'b0),                                            // (terminated)
		.csr_readdata      (),                                                // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),            // (terminated)
		.almost_full_data  (),                                                // (terminated)
		.almost_empty_data (),                                                // (terminated)
		.in_startofpacket  (1'b0),                                            // (terminated)
		.in_endofpacket    (1'b0),                                            // (terminated)
		.out_startofpacket (),                                                // (terminated)
		.out_endofpacket   (),                                                // (terminated)
		.in_empty          (1'b0),                                            // (terminated)
		.out_empty         (),                                                // (terminated)
		.in_error          (1'b0),                                            // (terminated)
		.out_error         (),                                                // (terminated)
		.in_channel        (1'b0),                                            // (terminated)
		.out_channel       ()                                                 // (terminated)
	);

	ghrd_10as066n2_altera_merlin_router_161_sptr6qy router (
		.sink_ready         (arria10_hps_h2f_axi_master_agent_write_cp_ready),                        //      sink.ready
		.sink_valid         (arria10_hps_h2f_axi_master_agent_write_cp_valid),                        //          .valid
		.sink_data          (arria10_hps_h2f_axi_master_agent_write_cp_data),                         //          .data
		.sink_startofpacket (arria10_hps_h2f_axi_master_agent_write_cp_startofpacket),                //          .startofpacket
		.sink_endofpacket   (arria10_hps_h2f_axi_master_agent_write_cp_endofpacket),                  //          .endofpacket
		.clk                (clk_0_clk_clk),                                                          //       clk.clk
		.reset              (arria10_hps_h2f_axi_master_agent_clk_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_src_ready),                                                       //       src.ready
		.src_valid          (router_src_valid),                                                       //          .valid
		.src_data           (router_src_data),                                                        //          .data
		.src_channel        (router_src_channel),                                                     //          .channel
		.src_startofpacket  (router_src_startofpacket),                                               //          .startofpacket
		.src_endofpacket    (router_src_endofpacket)                                                  //          .endofpacket
	);

	ghrd_10as066n2_altera_merlin_router_161_sptr6qy router_001 (
		.sink_ready         (arria10_hps_h2f_axi_master_agent_read_cp_ready),                         //      sink.ready
		.sink_valid         (arria10_hps_h2f_axi_master_agent_read_cp_valid),                         //          .valid
		.sink_data          (arria10_hps_h2f_axi_master_agent_read_cp_data),                          //          .data
		.sink_startofpacket (arria10_hps_h2f_axi_master_agent_read_cp_startofpacket),                 //          .startofpacket
		.sink_endofpacket   (arria10_hps_h2f_axi_master_agent_read_cp_endofpacket),                   //          .endofpacket
		.clk                (clk_0_clk_clk),                                                          //       clk.clk
		.reset              (arria10_hps_h2f_axi_master_agent_clk_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_001_src_ready),                                                   //       src.ready
		.src_valid          (router_001_src_valid),                                                   //          .valid
		.src_data           (router_001_src_data),                                                    //          .data
		.src_channel        (router_001_src_channel),                                                 //          .channel
		.src_startofpacket  (router_001_src_startofpacket),                                           //          .startofpacket
		.src_endofpacket    (router_001_src_endofpacket)                                              //          .endofpacket
	);

	ghrd_10as066n2_altera_merlin_router_161_ukrlwxa router_002 (
		.sink_ready         (agent_pipeline_001_source0_ready),                //      sink.ready
		.sink_valid         (agent_pipeline_001_source0_valid),                //          .valid
		.sink_data          (agent_pipeline_001_source0_data),                 //          .data
		.sink_startofpacket (agent_pipeline_001_source0_startofpacket),        //          .startofpacket
		.sink_endofpacket   (agent_pipeline_001_source0_endofpacket),          //          .endofpacket
		.clk                (clk_0_clk_clk),                                   //       clk.clk
		.reset              (sys_inti_mem_reset1_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_002_src_ready),                            //       src.ready
		.src_valid          (router_002_src_valid),                            //          .valid
		.src_data           (router_002_src_data),                             //          .data
		.src_channel        (router_002_src_channel),                          //          .channel
		.src_startofpacket  (router_002_src_startofpacket),                    //          .startofpacket
		.src_endofpacket    (router_002_src_endofpacket)                       //          .endofpacket
	);

	altera_merlin_burst_adapter #(
		.PKT_ADDR_H                (40),
		.PKT_ADDR_L                (9),
		.PKT_BEGIN_BURST           (74),
		.PKT_BYTE_CNT_H            (54),
		.PKT_BYTE_CNT_L            (47),
		.PKT_BYTEEN_H              (8),
		.PKT_BYTEEN_L              (8),
		.PKT_BURST_SIZE_H          (65),
		.PKT_BURST_SIZE_L          (63),
		.PKT_BURST_TYPE_H          (67),
		.PKT_BURST_TYPE_L          (66),
		.PKT_BURSTWRAP_H           (62),
		.PKT_BURSTWRAP_L           (55),
		.PKT_TRANS_COMPRESSED_READ (41),
		.PKT_TRANS_WRITE           (43),
		.PKT_TRANS_READ            (44),
		.OUT_NARROW_SIZE           (0),
		.IN_NARROW_SIZE            (1),
		.OUT_FIXED                 (0),
		.OUT_COMPLETE_WRAP         (0),
		.ST_DATA_W                 (94),
		.ST_CHANNEL_W              (2),
		.OUT_BYTE_CNT_H            (47),
		.OUT_BURSTWRAP_H           (62),
		.COMPRESSED_READ_SUPPORT   (1),
		.BYTEENABLE_SYNTHESIS      (1),
		.PIPE_INPUTS               (0),
		.NO_WRAP_SUPPORT           (0),
		.INCOMPLETE_WRAP_SUPPORT   (0),
		.BURSTWRAP_CONST_MASK      (0),
		.BURSTWRAP_CONST_VALUE     (0),
		.ADAPTER_VERSION           ("13.1")
	) sys_inti_mem_s1_burst_adapter (
		.clk                   (clk_0_clk_clk),                                       //       cr0.clk
		.reset                 (sys_inti_mem_reset1_reset_bridge_in_reset_reset),     // cr0_reset.reset
		.sink0_valid           (sys_inti_mem_s1_cmd_width_adapter_src_valid),         //     sink0.valid
		.sink0_data            (sys_inti_mem_s1_cmd_width_adapter_src_data),          //          .data
		.sink0_channel         (sys_inti_mem_s1_cmd_width_adapter_src_channel),       //          .channel
		.sink0_startofpacket   (sys_inti_mem_s1_cmd_width_adapter_src_startofpacket), //          .startofpacket
		.sink0_endofpacket     (sys_inti_mem_s1_cmd_width_adapter_src_endofpacket),   //          .endofpacket
		.sink0_ready           (sys_inti_mem_s1_cmd_width_adapter_src_ready),         //          .ready
		.source0_valid         (sys_inti_mem_s1_burst_adapter_source0_valid),         //   source0.valid
		.source0_data          (sys_inti_mem_s1_burst_adapter_source0_data),          //          .data
		.source0_channel       (sys_inti_mem_s1_burst_adapter_source0_channel),       //          .channel
		.source0_startofpacket (sys_inti_mem_s1_burst_adapter_source0_startofpacket), //          .startofpacket
		.source0_endofpacket   (sys_inti_mem_s1_burst_adapter_source0_endofpacket),   //          .endofpacket
		.source0_ready         (sys_inti_mem_s1_burst_adapter_source0_ready)          //          .ready
	);

	ghrd_10as066n2_altera_merlin_demultiplexer_161_ndeexqi cmd_demux (
		.clk                (clk_0_clk_clk),                                                          //       clk.clk
		.reset              (arria10_hps_h2f_axi_master_agent_clk_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_src_ready),                                                       //      sink.ready
		.sink_channel       (router_src_channel),                                                     //          .channel
		.sink_data          (router_src_data),                                                        //          .data
		.sink_startofpacket (router_src_startofpacket),                                               //          .startofpacket
		.sink_endofpacket   (router_src_endofpacket),                                                 //          .endofpacket
		.sink_valid         (router_src_valid),                                                       //          .valid
		.src0_ready         (cmd_demux_src0_ready),                                                   //      src0.ready
		.src0_valid         (cmd_demux_src0_valid),                                                   //          .valid
		.src0_data          (cmd_demux_src0_data),                                                    //          .data
		.src0_channel       (cmd_demux_src0_channel),                                                 //          .channel
		.src0_startofpacket (cmd_demux_src0_startofpacket),                                           //          .startofpacket
		.src0_endofpacket   (cmd_demux_src0_endofpacket)                                              //          .endofpacket
	);

	ghrd_10as066n2_altera_merlin_demultiplexer_161_ndeexqi cmd_demux_001 (
		.clk                (clk_0_clk_clk),                                                          //       clk.clk
		.reset              (arria10_hps_h2f_axi_master_agent_clk_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_001_src_ready),                                                   //      sink.ready
		.sink_channel       (router_001_src_channel),                                                 //          .channel
		.sink_data          (router_001_src_data),                                                    //          .data
		.sink_startofpacket (router_001_src_startofpacket),                                           //          .startofpacket
		.sink_endofpacket   (router_001_src_endofpacket),                                             //          .endofpacket
		.sink_valid         (router_001_src_valid),                                                   //          .valid
		.src0_ready         (cmd_demux_001_src0_ready),                                               //      src0.ready
		.src0_valid         (cmd_demux_001_src0_valid),                                               //          .valid
		.src0_data          (cmd_demux_001_src0_data),                                                //          .data
		.src0_channel       (cmd_demux_001_src0_channel),                                             //          .channel
		.src0_startofpacket (cmd_demux_001_src0_startofpacket),                                       //          .startofpacket
		.src0_endofpacket   (cmd_demux_001_src0_endofpacket)                                          //          .endofpacket
	);

	ghrd_10as066n2_altera_merlin_multiplexer_161_tetq7vi cmd_mux (
		.clk                 (clk_0_clk_clk),                                   //       clk.clk
		.reset               (sys_inti_mem_reset1_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (cmd_mux_src_ready),                               //       src.ready
		.src_valid           (cmd_mux_src_valid),                               //          .valid
		.src_data            (cmd_mux_src_data),                                //          .data
		.src_channel         (cmd_mux_src_channel),                             //          .channel
		.src_startofpacket   (cmd_mux_src_startofpacket),                       //          .startofpacket
		.src_endofpacket     (cmd_mux_src_endofpacket),                         //          .endofpacket
		.sink0_ready         (mux_pipeline_source0_ready),                      //     sink0.ready
		.sink0_valid         (mux_pipeline_source0_valid),                      //          .valid
		.sink0_channel       (mux_pipeline_source0_channel),                    //          .channel
		.sink0_data          (mux_pipeline_source0_data),                       //          .data
		.sink0_startofpacket (mux_pipeline_source0_startofpacket),              //          .startofpacket
		.sink0_endofpacket   (mux_pipeline_source0_endofpacket),                //          .endofpacket
		.sink1_ready         (mux_pipeline_001_source0_ready),                  //     sink1.ready
		.sink1_valid         (mux_pipeline_001_source0_valid),                  //          .valid
		.sink1_channel       (mux_pipeline_001_source0_channel),                //          .channel
		.sink1_data          (mux_pipeline_001_source0_data),                   //          .data
		.sink1_startofpacket (mux_pipeline_001_source0_startofpacket),          //          .startofpacket
		.sink1_endofpacket   (mux_pipeline_001_source0_endofpacket)             //          .endofpacket
	);

	ghrd_10as066n2_altera_merlin_demultiplexer_161_afxevna rsp_demux (
		.clk                (clk_0_clk_clk),                                       //       clk.clk
		.reset              (sys_inti_mem_reset1_reset_bridge_in_reset_reset),     // clk_reset.reset
		.sink_ready         (sys_inti_mem_s1_rsp_width_adapter_src_ready),         //      sink.ready
		.sink_channel       (sys_inti_mem_s1_rsp_width_adapter_src_channel),       //          .channel
		.sink_data          (sys_inti_mem_s1_rsp_width_adapter_src_data),          //          .data
		.sink_startofpacket (sys_inti_mem_s1_rsp_width_adapter_src_startofpacket), //          .startofpacket
		.sink_endofpacket   (sys_inti_mem_s1_rsp_width_adapter_src_endofpacket),   //          .endofpacket
		.sink_valid         (sys_inti_mem_s1_rsp_width_adapter_src_valid),         //          .valid
		.src0_ready         (rsp_demux_src0_ready),                                //      src0.ready
		.src0_valid         (rsp_demux_src0_valid),                                //          .valid
		.src0_data          (rsp_demux_src0_data),                                 //          .data
		.src0_channel       (rsp_demux_src0_channel),                              //          .channel
		.src0_startofpacket (rsp_demux_src0_startofpacket),                        //          .startofpacket
		.src0_endofpacket   (rsp_demux_src0_endofpacket),                          //          .endofpacket
		.src1_ready         (rsp_demux_src1_ready),                                //      src1.ready
		.src1_valid         (rsp_demux_src1_valid),                                //          .valid
		.src1_data          (rsp_demux_src1_data),                                 //          .data
		.src1_channel       (rsp_demux_src1_channel),                              //          .channel
		.src1_startofpacket (rsp_demux_src1_startofpacket),                        //          .startofpacket
		.src1_endofpacket   (rsp_demux_src1_endofpacket)                           //          .endofpacket
	);

	ghrd_10as066n2_altera_merlin_multiplexer_161_qcyoloy rsp_mux (
		.clk                 (clk_0_clk_clk),                                                          //       clk.clk
		.reset               (arria10_hps_h2f_axi_master_agent_clk_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (rsp_mux_src_ready),                                                      //       src.ready
		.src_valid           (rsp_mux_src_valid),                                                      //          .valid
		.src_data            (rsp_mux_src_data),                                                       //          .data
		.src_channel         (rsp_mux_src_channel),                                                    //          .channel
		.src_startofpacket   (rsp_mux_src_startofpacket),                                              //          .startofpacket
		.src_endofpacket     (rsp_mux_src_endofpacket),                                                //          .endofpacket
		.sink0_ready         (mux_pipeline_002_source0_ready),                                         //     sink0.ready
		.sink0_valid         (mux_pipeline_002_source0_valid),                                         //          .valid
		.sink0_channel       (mux_pipeline_002_source0_channel),                                       //          .channel
		.sink0_data          (mux_pipeline_002_source0_data),                                          //          .data
		.sink0_startofpacket (mux_pipeline_002_source0_startofpacket),                                 //          .startofpacket
		.sink0_endofpacket   (mux_pipeline_002_source0_endofpacket)                                    //          .endofpacket
	);

	ghrd_10as066n2_altera_merlin_multiplexer_161_qcyoloy rsp_mux_001 (
		.clk                 (clk_0_clk_clk),                                                          //       clk.clk
		.reset               (arria10_hps_h2f_axi_master_agent_clk_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (rsp_mux_001_src_ready),                                                  //       src.ready
		.src_valid           (rsp_mux_001_src_valid),                                                  //          .valid
		.src_data            (rsp_mux_001_src_data),                                                   //          .data
		.src_channel         (rsp_mux_001_src_channel),                                                //          .channel
		.src_startofpacket   (rsp_mux_001_src_startofpacket),                                          //          .startofpacket
		.src_endofpacket     (rsp_mux_001_src_endofpacket),                                            //          .endofpacket
		.sink0_ready         (mux_pipeline_003_source0_ready),                                         //     sink0.ready
		.sink0_valid         (mux_pipeline_003_source0_valid),                                         //          .valid
		.sink0_channel       (mux_pipeline_003_source0_channel),                                       //          .channel
		.sink0_data          (mux_pipeline_003_source0_data),                                          //          .data
		.sink0_startofpacket (mux_pipeline_003_source0_startofpacket),                                 //          .startofpacket
		.sink0_endofpacket   (mux_pipeline_003_source0_endofpacket)                                    //          .endofpacket
	);

	altera_merlin_width_adapter #(
		.IN_PKT_ADDR_H                 (40),
		.IN_PKT_ADDR_L                 (9),
		.IN_PKT_DATA_H                 (7),
		.IN_PKT_DATA_L                 (0),
		.IN_PKT_BYTEEN_H               (8),
		.IN_PKT_BYTEEN_L               (8),
		.IN_PKT_BYTE_CNT_H             (54),
		.IN_PKT_BYTE_CNT_L             (47),
		.IN_PKT_TRANS_COMPRESSED_READ  (41),
		.IN_PKT_TRANS_WRITE            (43),
		.IN_PKT_BURSTWRAP_H            (62),
		.IN_PKT_BURSTWRAP_L            (55),
		.IN_PKT_BURST_SIZE_H           (65),
		.IN_PKT_BURST_SIZE_L           (63),
		.IN_PKT_RESPONSE_STATUS_H      (90),
		.IN_PKT_RESPONSE_STATUS_L      (89),
		.IN_PKT_TRANS_EXCLUSIVE        (46),
		.IN_PKT_BURST_TYPE_H           (67),
		.IN_PKT_BURST_TYPE_L           (66),
		.IN_PKT_ORI_BURST_SIZE_L       (91),
		.IN_PKT_ORI_BURST_SIZE_H       (93),
		.IN_ST_DATA_W                  (94),
		.OUT_PKT_ADDR_H                (103),
		.OUT_PKT_ADDR_L                (72),
		.OUT_PKT_DATA_H                (63),
		.OUT_PKT_DATA_L                (0),
		.OUT_PKT_BYTEEN_H              (71),
		.OUT_PKT_BYTEEN_L              (64),
		.OUT_PKT_BYTE_CNT_H            (117),
		.OUT_PKT_BYTE_CNT_L            (110),
		.OUT_PKT_TRANS_COMPRESSED_READ (104),
		.OUT_PKT_BURST_SIZE_H          (128),
		.OUT_PKT_BURST_SIZE_L          (126),
		.OUT_PKT_RESPONSE_STATUS_H     (153),
		.OUT_PKT_RESPONSE_STATUS_L     (152),
		.OUT_PKT_TRANS_EXCLUSIVE       (109),
		.OUT_PKT_BURST_TYPE_H          (130),
		.OUT_PKT_BURST_TYPE_L          (129),
		.OUT_PKT_ORI_BURST_SIZE_L      (154),
		.OUT_PKT_ORI_BURST_SIZE_H      (156),
		.OUT_ST_DATA_W                 (157),
		.ST_CHANNEL_W                  (2),
		.OPTIMIZE_FOR_RSP              (0),
		.RESPONSE_PATH                 (1),
		.CONSTANT_BURST_SIZE           (0),
		.PACKING                       (1),
		.ENABLE_ADDRESS_ALIGNMENT      (1)
	) sys_inti_mem_s1_rsp_width_adapter (
		.clk                  (clk_0_clk_clk),                                       //       clk.clk
		.reset                (sys_inti_mem_reset1_reset_bridge_in_reset_reset),     // clk_reset.reset
		.in_valid             (router_002_src_valid),                                //      sink.valid
		.in_channel           (router_002_src_channel),                              //          .channel
		.in_startofpacket     (router_002_src_startofpacket),                        //          .startofpacket
		.in_endofpacket       (router_002_src_endofpacket),                          //          .endofpacket
		.in_ready             (router_002_src_ready),                                //          .ready
		.in_data              (router_002_src_data),                                 //          .data
		.out_endofpacket      (sys_inti_mem_s1_rsp_width_adapter_src_endofpacket),   //       src.endofpacket
		.out_data             (sys_inti_mem_s1_rsp_width_adapter_src_data),          //          .data
		.out_channel          (sys_inti_mem_s1_rsp_width_adapter_src_channel),       //          .channel
		.out_valid            (sys_inti_mem_s1_rsp_width_adapter_src_valid),         //          .valid
		.out_ready            (sys_inti_mem_s1_rsp_width_adapter_src_ready),         //          .ready
		.out_startofpacket    (sys_inti_mem_s1_rsp_width_adapter_src_startofpacket), //          .startofpacket
		.in_command_size_data (3'b000)                                               // (terminated)
	);

	altera_merlin_width_adapter #(
		.IN_PKT_ADDR_H                 (103),
		.IN_PKT_ADDR_L                 (72),
		.IN_PKT_DATA_H                 (63),
		.IN_PKT_DATA_L                 (0),
		.IN_PKT_BYTEEN_H               (71),
		.IN_PKT_BYTEEN_L               (64),
		.IN_PKT_BYTE_CNT_H             (117),
		.IN_PKT_BYTE_CNT_L             (110),
		.IN_PKT_TRANS_COMPRESSED_READ  (104),
		.IN_PKT_TRANS_WRITE            (106),
		.IN_PKT_BURSTWRAP_H            (125),
		.IN_PKT_BURSTWRAP_L            (118),
		.IN_PKT_BURST_SIZE_H           (128),
		.IN_PKT_BURST_SIZE_L           (126),
		.IN_PKT_RESPONSE_STATUS_H      (153),
		.IN_PKT_RESPONSE_STATUS_L      (152),
		.IN_PKT_TRANS_EXCLUSIVE        (109),
		.IN_PKT_BURST_TYPE_H           (130),
		.IN_PKT_BURST_TYPE_L           (129),
		.IN_PKT_ORI_BURST_SIZE_L       (154),
		.IN_PKT_ORI_BURST_SIZE_H       (156),
		.IN_ST_DATA_W                  (157),
		.OUT_PKT_ADDR_H                (40),
		.OUT_PKT_ADDR_L                (9),
		.OUT_PKT_DATA_H                (7),
		.OUT_PKT_DATA_L                (0),
		.OUT_PKT_BYTEEN_H              (8),
		.OUT_PKT_BYTEEN_L              (8),
		.OUT_PKT_BYTE_CNT_H            (54),
		.OUT_PKT_BYTE_CNT_L            (47),
		.OUT_PKT_TRANS_COMPRESSED_READ (41),
		.OUT_PKT_BURST_SIZE_H          (65),
		.OUT_PKT_BURST_SIZE_L          (63),
		.OUT_PKT_RESPONSE_STATUS_H     (90),
		.OUT_PKT_RESPONSE_STATUS_L     (89),
		.OUT_PKT_TRANS_EXCLUSIVE       (46),
		.OUT_PKT_BURST_TYPE_H          (67),
		.OUT_PKT_BURST_TYPE_L          (66),
		.OUT_PKT_ORI_BURST_SIZE_L      (91),
		.OUT_PKT_ORI_BURST_SIZE_H      (93),
		.OUT_ST_DATA_W                 (94),
		.ST_CHANNEL_W                  (2),
		.OPTIMIZE_FOR_RSP              (0),
		.RESPONSE_PATH                 (0),
		.CONSTANT_BURST_SIZE           (0),
		.PACKING                       (0),
		.ENABLE_ADDRESS_ALIGNMENT      (1)
	) sys_inti_mem_s1_cmd_width_adapter (
		.clk                  (clk_0_clk_clk),                                       //       clk.clk
		.reset                (sys_inti_mem_reset1_reset_bridge_in_reset_reset),     // clk_reset.reset
		.in_valid             (cmd_mux_src_valid),                                   //      sink.valid
		.in_channel           (cmd_mux_src_channel),                                 //          .channel
		.in_startofpacket     (cmd_mux_src_startofpacket),                           //          .startofpacket
		.in_endofpacket       (cmd_mux_src_endofpacket),                             //          .endofpacket
		.in_ready             (cmd_mux_src_ready),                                   //          .ready
		.in_data              (cmd_mux_src_data),                                    //          .data
		.out_endofpacket      (sys_inti_mem_s1_cmd_width_adapter_src_endofpacket),   //       src.endofpacket
		.out_data             (sys_inti_mem_s1_cmd_width_adapter_src_data),          //          .data
		.out_channel          (sys_inti_mem_s1_cmd_width_adapter_src_channel),       //          .channel
		.out_valid            (sys_inti_mem_s1_cmd_width_adapter_src_valid),         //          .valid
		.out_ready            (sys_inti_mem_s1_cmd_width_adapter_src_ready),         //          .ready
		.out_startofpacket    (sys_inti_mem_s1_cmd_width_adapter_src_startofpacket), //          .startofpacket
		.in_command_size_data (3'b000)                                               // (terminated)
	);

	altera_avalon_st_pipeline_stage #(
		.SYMBOLS_PER_BEAT (1),
		.BITS_PER_SYMBOL  (94),
		.USE_PACKETS      (1),
		.USE_EMPTY        (0),
		.EMPTY_WIDTH      (0),
		.CHANNEL_WIDTH    (2),
		.PACKET_WIDTH     (2),
		.ERROR_WIDTH      (0),
		.PIPELINE_READY   (1)
	) agent_pipeline (
		.clk               (clk_0_clk_clk),                                       //       cr0.clk
		.reset             (sys_inti_mem_reset1_reset_bridge_in_reset_reset),     // cr0_reset.reset
		.in_ready          (sys_inti_mem_s1_burst_adapter_source0_ready),         //     sink0.ready
		.in_valid          (sys_inti_mem_s1_burst_adapter_source0_valid),         //          .valid
		.in_startofpacket  (sys_inti_mem_s1_burst_adapter_source0_startofpacket), //          .startofpacket
		.in_endofpacket    (sys_inti_mem_s1_burst_adapter_source0_endofpacket),   //          .endofpacket
		.in_data           (sys_inti_mem_s1_burst_adapter_source0_data),          //          .data
		.in_channel        (sys_inti_mem_s1_burst_adapter_source0_channel),       //          .channel
		.out_ready         (agent_pipeline_source0_ready),                        //   source0.ready
		.out_valid         (agent_pipeline_source0_valid),                        //          .valid
		.out_startofpacket (agent_pipeline_source0_startofpacket),                //          .startofpacket
		.out_endofpacket   (agent_pipeline_source0_endofpacket),                  //          .endofpacket
		.out_data          (agent_pipeline_source0_data),                         //          .data
		.out_channel       (agent_pipeline_source0_channel),                      //          .channel
		.in_empty          (1'b0),                                                // (terminated)
		.out_empty         (),                                                    // (terminated)
		.out_error         (),                                                    // (terminated)
		.in_error          (1'b0)                                                 // (terminated)
	);

	altera_avalon_st_pipeline_stage #(
		.SYMBOLS_PER_BEAT (1),
		.BITS_PER_SYMBOL  (94),
		.USE_PACKETS      (1),
		.USE_EMPTY        (0),
		.EMPTY_WIDTH      (0),
		.CHANNEL_WIDTH    (0),
		.PACKET_WIDTH     (2),
		.ERROR_WIDTH      (0),
		.PIPELINE_READY   (1)
	) agent_pipeline_001 (
		.clk               (clk_0_clk_clk),                                   //       cr0.clk
		.reset             (sys_inti_mem_reset1_reset_bridge_in_reset_reset), // cr0_reset.reset
		.in_ready          (sys_inti_mem_s1_agent_rp_ready),                  //     sink0.ready
		.in_valid          (sys_inti_mem_s1_agent_rp_valid),                  //          .valid
		.in_startofpacket  (sys_inti_mem_s1_agent_rp_startofpacket),          //          .startofpacket
		.in_endofpacket    (sys_inti_mem_s1_agent_rp_endofpacket),            //          .endofpacket
		.in_data           (sys_inti_mem_s1_agent_rp_data),                   //          .data
		.out_ready         (agent_pipeline_001_source0_ready),                //   source0.ready
		.out_valid         (agent_pipeline_001_source0_valid),                //          .valid
		.out_startofpacket (agent_pipeline_001_source0_startofpacket),        //          .startofpacket
		.out_endofpacket   (agent_pipeline_001_source0_endofpacket),          //          .endofpacket
		.out_data          (agent_pipeline_001_source0_data),                 //          .data
		.in_empty          (1'b0),                                            // (terminated)
		.out_empty         (),                                                // (terminated)
		.out_error         (),                                                // (terminated)
		.in_error          (1'b0),                                            // (terminated)
		.out_channel       (),                                                // (terminated)
		.in_channel        (1'b0)                                             // (terminated)
	);

	altera_avalon_st_pipeline_stage #(
		.SYMBOLS_PER_BEAT (1),
		.BITS_PER_SYMBOL  (157),
		.USE_PACKETS      (1),
		.USE_EMPTY        (0),
		.EMPTY_WIDTH      (0),
		.CHANNEL_WIDTH    (2),
		.PACKET_WIDTH     (2),
		.ERROR_WIDTH      (0),
		.PIPELINE_READY   (1)
	) mux_pipeline (
		.clk               (clk_0_clk_clk),                                   //       cr0.clk
		.reset             (sys_inti_mem_reset1_reset_bridge_in_reset_reset), // cr0_reset.reset
		.in_ready          (cmd_demux_src0_ready),                            //     sink0.ready
		.in_valid          (cmd_demux_src0_valid),                            //          .valid
		.in_startofpacket  (cmd_demux_src0_startofpacket),                    //          .startofpacket
		.in_endofpacket    (cmd_demux_src0_endofpacket),                      //          .endofpacket
		.in_data           (cmd_demux_src0_data),                             //          .data
		.in_channel        (cmd_demux_src0_channel),                          //          .channel
		.out_ready         (mux_pipeline_source0_ready),                      //   source0.ready
		.out_valid         (mux_pipeline_source0_valid),                      //          .valid
		.out_startofpacket (mux_pipeline_source0_startofpacket),              //          .startofpacket
		.out_endofpacket   (mux_pipeline_source0_endofpacket),                //          .endofpacket
		.out_data          (mux_pipeline_source0_data),                       //          .data
		.out_channel       (mux_pipeline_source0_channel),                    //          .channel
		.in_empty          (1'b0),                                            // (terminated)
		.out_empty         (),                                                // (terminated)
		.out_error         (),                                                // (terminated)
		.in_error          (1'b0)                                             // (terminated)
	);

	altera_avalon_st_pipeline_stage #(
		.SYMBOLS_PER_BEAT (1),
		.BITS_PER_SYMBOL  (157),
		.USE_PACKETS      (1),
		.USE_EMPTY        (0),
		.EMPTY_WIDTH      (0),
		.CHANNEL_WIDTH    (2),
		.PACKET_WIDTH     (2),
		.ERROR_WIDTH      (0),
		.PIPELINE_READY   (1)
	) mux_pipeline_001 (
		.clk               (clk_0_clk_clk),                                   //       cr0.clk
		.reset             (sys_inti_mem_reset1_reset_bridge_in_reset_reset), // cr0_reset.reset
		.in_ready          (cmd_demux_001_src0_ready),                        //     sink0.ready
		.in_valid          (cmd_demux_001_src0_valid),                        //          .valid
		.in_startofpacket  (cmd_demux_001_src0_startofpacket),                //          .startofpacket
		.in_endofpacket    (cmd_demux_001_src0_endofpacket),                  //          .endofpacket
		.in_data           (cmd_demux_001_src0_data),                         //          .data
		.in_channel        (cmd_demux_001_src0_channel),                      //          .channel
		.out_ready         (mux_pipeline_001_source0_ready),                  //   source0.ready
		.out_valid         (mux_pipeline_001_source0_valid),                  //          .valid
		.out_startofpacket (mux_pipeline_001_source0_startofpacket),          //          .startofpacket
		.out_endofpacket   (mux_pipeline_001_source0_endofpacket),            //          .endofpacket
		.out_data          (mux_pipeline_001_source0_data),                   //          .data
		.out_channel       (mux_pipeline_001_source0_channel),                //          .channel
		.in_empty          (1'b0),                                            // (terminated)
		.out_empty         (),                                                // (terminated)
		.out_error         (),                                                // (terminated)
		.in_error          (1'b0)                                             // (terminated)
	);

	altera_avalon_st_pipeline_stage #(
		.SYMBOLS_PER_BEAT (1),
		.BITS_PER_SYMBOL  (157),
		.USE_PACKETS      (1),
		.USE_EMPTY        (0),
		.EMPTY_WIDTH      (0),
		.CHANNEL_WIDTH    (2),
		.PACKET_WIDTH     (2),
		.ERROR_WIDTH      (0),
		.PIPELINE_READY   (1)
	) mux_pipeline_002 (
		.clk               (clk_0_clk_clk),                                                          //       cr0.clk
		.reset             (arria10_hps_h2f_axi_master_agent_clk_reset_reset_bridge_in_reset_reset), // cr0_reset.reset
		.in_ready          (rsp_demux_src0_ready),                                                   //     sink0.ready
		.in_valid          (rsp_demux_src0_valid),                                                   //          .valid
		.in_startofpacket  (rsp_demux_src0_startofpacket),                                           //          .startofpacket
		.in_endofpacket    (rsp_demux_src0_endofpacket),                                             //          .endofpacket
		.in_data           (rsp_demux_src0_data),                                                    //          .data
		.in_channel        (rsp_demux_src0_channel),                                                 //          .channel
		.out_ready         (mux_pipeline_002_source0_ready),                                         //   source0.ready
		.out_valid         (mux_pipeline_002_source0_valid),                                         //          .valid
		.out_startofpacket (mux_pipeline_002_source0_startofpacket),                                 //          .startofpacket
		.out_endofpacket   (mux_pipeline_002_source0_endofpacket),                                   //          .endofpacket
		.out_data          (mux_pipeline_002_source0_data),                                          //          .data
		.out_channel       (mux_pipeline_002_source0_channel),                                       //          .channel
		.in_empty          (1'b0),                                                                   // (terminated)
		.out_empty         (),                                                                       // (terminated)
		.out_error         (),                                                                       // (terminated)
		.in_error          (1'b0)                                                                    // (terminated)
	);

	altera_avalon_st_pipeline_stage #(
		.SYMBOLS_PER_BEAT (1),
		.BITS_PER_SYMBOL  (157),
		.USE_PACKETS      (1),
		.USE_EMPTY        (0),
		.EMPTY_WIDTH      (0),
		.CHANNEL_WIDTH    (2),
		.PACKET_WIDTH     (2),
		.ERROR_WIDTH      (0),
		.PIPELINE_READY   (1)
	) mux_pipeline_003 (
		.clk               (clk_0_clk_clk),                                                          //       cr0.clk
		.reset             (arria10_hps_h2f_axi_master_agent_clk_reset_reset_bridge_in_reset_reset), // cr0_reset.reset
		.in_ready          (rsp_demux_src1_ready),                                                   //     sink0.ready
		.in_valid          (rsp_demux_src1_valid),                                                   //          .valid
		.in_startofpacket  (rsp_demux_src1_startofpacket),                                           //          .startofpacket
		.in_endofpacket    (rsp_demux_src1_endofpacket),                                             //          .endofpacket
		.in_data           (rsp_demux_src1_data),                                                    //          .data
		.in_channel        (rsp_demux_src1_channel),                                                 //          .channel
		.out_ready         (mux_pipeline_003_source0_ready),                                         //   source0.ready
		.out_valid         (mux_pipeline_003_source0_valid),                                         //          .valid
		.out_startofpacket (mux_pipeline_003_source0_startofpacket),                                 //          .startofpacket
		.out_endofpacket   (mux_pipeline_003_source0_endofpacket),                                   //          .endofpacket
		.out_data          (mux_pipeline_003_source0_data),                                          //          .data
		.out_channel       (mux_pipeline_003_source0_channel),                                       //          .channel
		.in_empty          (1'b0),                                                                   // (terminated)
		.out_empty         (),                                                                       // (terminated)
		.out_error         (),                                                                       // (terminated)
		.in_error          (1'b0)                                                                    // (terminated)
	);

	ghrd_10as066n2_altera_avalon_st_adapter_161_4tryxxy #(
		.inBitsPerSymbol (10),
		.inUsePackets    (0),
		.inDataWidth     (10),
		.inChannelWidth  (0),
		.inErrorWidth    (0),
		.inUseEmptyPort  (0),
		.inUseValid      (1),
		.inUseReady      (1),
		.inReadyLatency  (0),
		.outDataWidth    (10),
		.outChannelWidth (0),
		.outErrorWidth   (1),
		.outUseEmptyPort (0),
		.outUseValid     (1),
		.outUseReady     (1),
		.outReadyLatency (0)
	) avalon_st_adapter (
		.in_clk_0_clk   (clk_0_clk_clk),                                   // in_clk_0.clk
		.in_rst_0_reset (sys_inti_mem_reset1_reset_bridge_in_reset_reset), // in_rst_0.reset
		.in_0_data      (sys_inti_mem_s1_agent_rdata_fifo_out_data),       //     in_0.data
		.in_0_valid     (sys_inti_mem_s1_agent_rdata_fifo_out_valid),      //         .valid
		.in_0_ready     (sys_inti_mem_s1_agent_rdata_fifo_out_ready),      //         .ready
		.out_0_data     (avalon_st_adapter_out_0_data),                    //    out_0.data
		.out_0_valid    (avalon_st_adapter_out_0_valid),                   //         .valid
		.out_0_ready    (avalon_st_adapter_out_0_ready),                   //         .ready
		.out_0_error    (avalon_st_adapter_out_0_error)                    //         .error
	);

endmodule
