config alt_sld_fab_alt_sld_fab_161_m5wqdqi_cfg;
		design alt_sld_fab_alt_sld_fab_161_m5wqdqi;
		instance alt_sld_fab_alt_sld_fab_161_m5wqdqi.presplit use alt_sld_fab_altera_super_splitter_161.alt_sld_fab_altera_super_splitter_161_vumttgi;
		instance alt_sld_fab_alt_sld_fab_161_m5wqdqi.splitter use alt_sld_fab_altera_sld_splitter_161.alt_sld_fab_altera_sld_splitter_161_agqapvy;
		instance alt_sld_fab_alt_sld_fab_161_m5wqdqi.sldfabric use alt_sld_fab_altera_sld_jtag_hub_161.alt_sld_fab_altera_sld_jtag_hub_161_wbfqiva;
		instance alt_sld_fab_alt_sld_fab_161_m5wqdqi.ident use alt_sld_fab_altera_connection_identification_hub_161.alt_sld_fab_altera_connection_identification_hub_161_iheo73y;
endconfig

