// ad_cmos_out_core_a10.v

// Generated using ACDS version 16.1 203

`timescale 1 ps / 1 ps
module ad_cmos_out_core_a10 (
		input  wire       clk_export,     //     clk.export
		input  wire [1:0] din_export,     //     din.export
		output wire [0:0] pad_out_export  // pad_out.export
	);

	ghrd_10as066n2_alt_serdes_10_v6injpq ad_cmos_out_core_a10 (
		.clk_export     (clk_export),     //     clk.export
		.din_export     (din_export),     //     din.export
		.pad_out_export (pad_out_export)  // pad_out.export
	);

endmodule
