// ad_serdes_clk_core.v

// Generated using ACDS version 16.1 203

`timescale 1 ps / 1 ps
module ad_serdes_clk_core (
		input  wire       rst_reset,       //      rst.reset
		input  wire       ref_clk_clk,     //  ref_clk.clk
		output wire       locked_export,   //   locked.export
		output wire [7:0] hs_phase_phout,  // hs_phase.phout
		output wire [1:0] hs_clk_lvds_clk, //   hs_clk.lvds_clk
		output wire [1:0] loaden_loaden,   //   loaden.loaden
		output wire       ls_clk_clk       //   ls_clk.clk
	);

	ghrd_10as066n2_alt_serdes_10_ruc4yeq ad_serdes_clk_core (
		.rst_reset       (rst_reset),       //      rst.reset
		.ref_clk_clk     (ref_clk_clk),     //  ref_clk.clk
		.locked_export   (locked_export),   //   locked.export
		.hs_phase_phout  (hs_phase_phout),  // hs_phase.phout
		.hs_clk_lvds_clk (hs_clk_lvds_clk), //   hs_clk.lvds_clk
		.loaden_loaden   (loaden_loaden),   //   loaden.loaden
		.ls_clk_clk      (ls_clk_clk)       //   ls_clk.clk
	);

endmodule
