// ad_serdes_in_core_a10.v

// Generated using ACDS version 16.1 203

`timescale 1 ps / 1 ps
module ad_serdes_in_core_a10 (
		input  wire [0:0] data_in_export,      //      data_in.export
		input  wire       clk_export,          //          clk.export
		input  wire       loaden_export,       //       loaden.export
		input  wire       div_clk_export,      //      div_clk.export
		input  wire [7:0] hs_phase_export,     //     hs_phase.export
		input  wire       locked_export,       //       locked.export
		output wire [3:0] data_s_export,       //       data_s.export
		output wire [0:0] delay_locked_export  // delay_locked.export
	);

	ghrd_10as066n2_alt_serdes_10_vaq6iza ad_serdes_in_core_a10 (
		.data_in_export      (data_in_export),      //      data_in.export
		.clk_export          (clk_export),          //          clk.export
		.loaden_export       (loaden_export),       //       loaden.export
		.div_clk_export      (div_clk_export),      //      div_clk.export
		.hs_phase_export     (hs_phase_export),     //     hs_phase.export
		.locked_export       (locked_export),       //       locked.export
		.data_s_export       (data_s_export),       //       data_s.export
		.delay_locked_export (delay_locked_export)  // delay_locked.export
	);

endmodule
