// ad_serdes_out_core_a10.v

// Generated using ACDS version 16.1 203

`timescale 1 ps / 1 ps
module ad_serdes_out_core_a10 (
		output wire [0:0] data_out_export, // data_out.export
		input  wire       clk_export,      //      clk.export
		input  wire       loaden_export,   //   loaden.export
		input  wire       div_clk_export,  //  div_clk.export
		input  wire [3:0] data_s_export    //   data_s.export
	);

	ghrd_10as066n2_alt_serdes_10_jgwqmpq ad_serdes_out_core_a10 (
		.data_out_export (data_out_export), // data_out.export
		.clk_export      (clk_export),      //      clk.export
		.loaden_export   (loaden_export),   //   loaden.export
		.div_clk_export  (div_clk_export),  //  div_clk.export
		.data_s_export   (data_s_export)    //   data_s.export
	);

endmodule
